#!/usr/bin/env python3
"""
Candy Trivia TikTok Factory — Safe Daily Publisher

Normal use from PowerShell:

    python .\candy_publish_today.py --dry-run
    python .\candy_publish_today.py

Safety goals:
- Never rewrite campaign schedule dates/times.
- Select the next campaign date that still has future posts (or --date YYYY-MM-DD).
- Never intentionally submit the same post twice.
- Persist publish state under .private/ so deleting out/ does not erase the safety record.
- Mark a post PUBLISHING before calling Buffer. If the process fails after that point,
  the post stays blocked as UNCERTAIN instead of being retried automatically.
- Also honor the existing Node manifest/publish ledger when present.

The default campaign generated by v2.7 starts 2026-09-01 with three posts per day.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any

try:
    from zoneinfo import ZoneInfo
except ImportError:
    ZoneInfo = None


DEFAULT_PROJECT = Path(r"C:\Users\perry\AI\ChatGPT\CandyTrivia-TikTok-Factor")
BRANCH = "feature/three-post-autopilot"
TIMEZONE = "America/Phoenix"
STATE_RELATIVE = Path(".private") / "candy-publisher-state.json"
POST_PATTERN = re.compile(r"^post-(\d{3})\.json$", re.IGNORECASE)


def banner(text: str) -> None:
    line = "=" * 76
    print(f"\n{line}\n{text}\n{line}")


def npm_command() -> str:
    return "npm.cmd" if os.name == "nt" else "npm"


def command_exists(name: str) -> bool:
    return shutil.which(name) is not None


def run(cmd: list[str], *, cwd: Path, label: str) -> None:
    print(f"\n>>> {label}")
    print("    " + " ".join(cmd))
    completed = subprocess.run(cmd, cwd=str(cwd), shell=False)
    if completed.returncode != 0:
        raise SystemExit(
            f"\nFAILED: {label}\n"
            f"Exit code: {completed.returncode}\n"
            "Nothing after this step was run."
        )


def find_project() -> Path:
    current = Path.cwd()
    if (current / "package.json").exists() and (current / "src").exists():
        return current
    if DEFAULT_PROJECT.exists():
        return DEFAULT_PROJECT
    raise SystemExit(
        "Could not locate CandyTrivia-TikTok-Factor.\n"
        "Run this script from the project folder or edit DEFAULT_PROJECT."
    )


def phoenix_now() -> datetime:
    if ZoneInfo is None:
        raise SystemExit("Python zoneinfo is unavailable.")
    return datetime.now(ZoneInfo(TIMEZONE))


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def save_json_atomic(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    temp.replace(path)


def parse_scheduled_at(value: str) -> datetime:
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise SystemExit(f"Invalid scheduledAt value: {value}") from exc
    if parsed.tzinfo is None:
        raise SystemExit(f"scheduledAt must include a timezone offset: {value}")
    return parsed.astimezone(ZoneInfo(TIMEZONE))


def canonical_content(data: dict[str, Any]) -> str:
    compact = {
        "q1": data.get("q1"),
        "q2": data.get("q2"),
        "q3": data.get("q3"),
        "caption": data.get("caption"),
    }
    return json.dumps(compact, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def content_fingerprint(data: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_content(data).encode("utf-8")).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_state(project: Path) -> tuple[Path, dict[str, Any]]:
    state_file = project / STATE_RELATIVE
    if not state_file.exists():
        return state_file, {"version": 1, "posts": {}}
    try:
        data = load_json(state_file)
    except Exception as exc:
        raise SystemExit(f"Could not read publisher state: {state_file}\n{exc}") from exc
    if not isinstance(data, dict):
        raise SystemExit(f"Publisher state is not a JSON object: {state_file}")
    data.setdefault("version", 1)
    data.setdefault("posts", {})
    return state_file, data


def read_json_lines(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        try:
            value = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            rows.append(value)
    return rows


def historical_sent_days(project: Path) -> dict[int, dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for candidate in [
        project / ".private" / "publish-ledger.jsonl",
        project / "out" / "publish-ledger.jsonl",
        project / "out" / "manifest.jsonl",
    ]:
        rows.extend(read_json_lines(candidate))

    sent: dict[int, dict[str, Any]] = {}
    for row in rows:
        day_value = row.get("day")
        try:
            day_num = int(day_value)
        except (TypeError, ValueError):
            continue
        sent[day_num] = row
    return sent


def discover_posts(project: Path) -> list[dict[str, Any]]:
    auto_dir = project / "examples" / "auto"
    if not auto_dir.exists():
        raise SystemExit(
            "examples\\auto does not exist. Generate/audit the v2.7 campaign first."
        )

    posts: list[dict[str, Any]] = []
    for path in sorted(auto_dir.iterdir()):
        match = POST_PATTERN.match(path.name)
        if not match:
            continue
        data = load_json(path)
        day_num = int(data.get("day", int(match.group(1))))
        scheduled_raw = data.get("scheduledAt")
        if not isinstance(scheduled_raw, str) or not scheduled_raw.strip():
            raise SystemExit(f"Missing scheduledAt in {path}")
        scheduled = parse_scheduled_at(scheduled_raw)
        posts.append(
            {
                "number": day_num,
                "path": path,
                "data": data,
                "scheduled": scheduled,
                "fingerprint": content_fingerprint(data),
            }
        )

    if not posts:
        raise SystemExit("No examples\\auto\\post-###.json files were found.")
    return posts


def choose_target_date(posts: list[dict[str, Any]], requested: date | None, now: datetime) -> date:
    dates = sorted({post["scheduled"].date() for post in posts})
    if requested is not None:
        if requested not in dates:
            available = ", ".join(d.isoformat() for d in dates)
            raise SystemExit(
                f"No campaign posts are scheduled for {requested.isoformat()}.\n"
                f"Available dates: {available}"
            )
        return requested

    today = now.date()
    today_future = [post for post in posts if post["scheduled"].date() == today and post["scheduled"] > now]
    if today_future:
        return today

    future_dates = [d for d in dates if d > today]
    if future_dates:
        return future_dates[0]

    if today in dates:
        return today

    raise SystemExit("The generated campaign has no current or future dates left to publish.")


def output_video(project: Path, post_number: int) -> Path:
    return project / "out" / f"candy-trivia-day-{post_number:03d}.mp4"


def verify_render(project: Path, post_number: int) -> Path:
    video = output_video(project, post_number)
    if not video.exists():
        raise SystemExit(f"Expected rendered video does not exist:\n  {video}")
    size_mb = video.stat().st_size / (1024 * 1024)
    if size_mb < 0.5:
        raise SystemExit(
            f"Rendered video looks suspiciously small ({size_mb:.2f} MB):\n  {video}"
        )
    print(f"Verified Post {post_number:03d}: {video.name} ({size_mb:.1f} MB)")
    return video


def latest_manifest_for_day(project: Path, post_number: int) -> dict[str, Any] | None:
    rows = read_json_lines(project / "out" / "manifest.jsonl")
    for row in reversed(rows):
        try:
            if int(row.get("day")) == post_number:
                return row
        except (TypeError, ValueError):
            continue
    return None


def mark_state(
    state_file: Path,
    state: dict[str, Any],
    post: dict[str, Any],
    *,
    status: str,
    now: datetime,
    video_sha: str | None = None,
    buffer_post_id: str | None = None,
) -> None:
    key = f"{post['number']:03d}"
    existing = dict(state["posts"].get(key, {}))
    existing.update(
        {
            "post": post["number"],
            "status": status,
            "scheduledAt": post["scheduled"].isoformat(timespec="seconds"),
            "contentFingerprint": post["fingerprint"],
            "updatedAt": now.isoformat(timespec="seconds"),
        }
    )
    if status == "PUBLISHING":
        existing["attemptedAt"] = now.isoformat(timespec="seconds")
    if status == "SENT":
        existing["completedAt"] = now.isoformat(timespec="seconds")
    if video_sha:
        existing["videoSha256"] = video_sha
    if buffer_post_id:
        existing["bufferPostId"] = buffer_post_id
    state["posts"][key] = existing
    save_json_atomic(state_file, state)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Safely publish the next Candy Trivia campaign day")
    parser.add_argument("--date", type=str, default=None, help="Campaign date YYYY-MM-DD. Default: today if future slots remain, otherwise next campaign date")
    parser.add_argument("--dry-run", action="store_true", help="Show exactly what would happen without rendering or publishing")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    banner("CANDY TRIVIA — SAFE DAILY PUBLISHER")

    project = find_project()
    npm = npm_command()
    now = phoenix_now()

    print(f"Project:\n  {project}")
    print(f"Branch:\n  {BRANCH}")
    print(f"Timezone:\n  {TIMEZONE}")
    print(f"Current local time:\n  {now.strftime('%Y-%m-%d %I:%M:%S %p %Z')}")

    if not command_exists("git"):
        raise SystemExit("Git was not found in PATH.")
    if not (command_exists("npm") or command_exists("npm.cmd")):
        raise SystemExit("npm was not found in PATH.")

    if not args.dry_run:
        banner("1. UPDATE PROJECT")
        run(["git", "checkout", BRANCH], cwd=project, label=f"Checkout {BRANCH}")
        run(["git", "pull", "--ff-only", "origin", BRANCH], cwd=project, label="Pull latest GitHub changes")
        run([npm, "run", "typecheck"], cwd=project, label="TypeScript typecheck")
    else:
        banner("1. DRY RUN — GIT/TYPECHECK SKIPPED")

    posts = discover_posts(project)
    requested_date = date.fromisoformat(args.date) if args.date else None
    target_date = choose_target_date(posts, requested_date, now)
    selected = [post for post in posts if post["scheduled"].date() == target_date]
    selected.sort(key=lambda post: post["scheduled"])

    if len(selected) > 3:
        raise SystemExit(f"Safety stop: found {len(selected)} posts for {target_date}; expected at most 3.")

    state_file, state = load_state(project)
    historical = historical_sent_days(project)

    banner(f"2. TARGET CAMPAIGN DATE — {target_date.isoformat()}")
    print(f"Persistent safety state:\n  {state_file}")

    eligible: list[dict[str, Any]] = []
    blocked_uncertain: list[int] = []
    skipped_sent: list[int] = []
    skipped_past: list[int] = []

    sent_fingerprints = {
        entry.get("contentFingerprint")
        for entry in state.get("posts", {}).values()
        if isinstance(entry, dict) and entry.get("status") == "SENT"
    }

    for post in selected:
        number = post["number"]
        key = f"{number:03d}"
        local = state.get("posts", {}).get(key, {})
        status = local.get("status") if isinstance(local, dict) else None

        print(f"\nPost {number:03d}  ->  {post['scheduled'].strftime('%Y-%m-%d %I:%M %p %Z')}")

        if number in historical:
            print("  SKIP: existing Node manifest/publish ledger says this post was already sent.")
            skipped_sent.append(number)
            continue

        if status == "SENT":
            print("  SKIP: persistent publisher state says SENT.")
            skipped_sent.append(number)
            continue

        if status == "PUBLISHING":
            print("  BLOCKED: previous attempt is PUBLISHING/UNCERTAIN. Automatic retry is disabled to prevent duplicates.")
            blocked_uncertain.append(number)
            continue

        if post["fingerprint"] in sent_fingerprints:
            print("  BLOCKED: identical content fingerprint was already sent under another post ID.")
            blocked_uncertain.append(number)
            continue

        if post["scheduled"] <= now:
            print("  SKIP: scheduled time is already in the past; this script will not burst-post it late.")
            skipped_past.append(number)
            continue

        print("  READY: new post, future schedule, no prior publish record.")
        eligible.append(post)

    if args.dry_run:
        banner("DRY RUN COMPLETE — NOTHING WAS PUBLISHED")
        print(f"Ready: {[f'{p['number']:03d}' for p in eligible]}")
        print(f"Already sent: {[f'{n:03d}' for n in skipped_sent]}")
        print(f"Uncertain/blocked: {[f'{n:03d}' for n in blocked_uncertain]}")
        print(f"Past-due skipped: {[f'{n:03d}' for n in skipped_past]}")
        return

    if not eligible:
        banner("NO NEW POSTS TO PUBLISH")
        print("Nothing was submitted to Buffer.")
        if blocked_uncertain:
            print("\nOne or more posts are intentionally blocked as UNCERTAIN. Verify Buffer/TikTok before changing their state.")
        return

    banner("3. RENDER ONLY NEW POSTS")
    rendered: dict[int, Path] = {}
    for post in eligible:
        number = post["number"]
        json_rel = post["path"].relative_to(project)
        run([npm, "run", "render-local", "--", str(json_rel)], cwd=project, label=f"Render Post {number:03d}")
        rendered[number] = verify_render(project, number)

    banner("4. PUBLISH WITH TWO-PHASE DUPLICATE PROTECTION")
    published: list[int] = []
    for post in eligible:
        number = post["number"]
        video = rendered[number]
        video_sha = file_sha256(video)
        attempt_time = phoenix_now()

        # Critical safety step: persist PUBLISHING BEFORE Buffer is called.
        # If anything becomes ambiguous after this point, a rerun will block instead of duplicate.
        mark_state(state_file, state, post, status="PUBLISHING", now=attempt_time, video_sha=video_sha)

        json_rel = post["path"].relative_to(project)
        print(
            f"\nPublishing Post {number:03d} for "
            f"{post['scheduled'].strftime('%Y-%m-%d %I:%M %p %Z')} ..."
        )
        try:
            run([npm, "run", "publish", "--", str(json_rel)], cwd=project, label=f"Publish Post {number:03d}")
        except SystemExit:
            print(
                f"\nSAFETY HOLD: Post {number:03d} remains PUBLISHING/UNCERTAIN.\n"
                "Do NOT rerun it automatically. Check Buffer/TikTok first."
            )
            raise

        manifest = latest_manifest_for_day(project, number) or {}
        buffer_id = manifest.get("bufferPostId") if isinstance(manifest, dict) else None
        mark_state(
            state_file,
            state,
            post,
            status="SENT",
            now=phoenix_now(),
            video_sha=video_sha,
            buffer_post_id=str(buffer_id) if buffer_id else None,
        )
        published.append(number)
        print(f"Post {number:03d}: SENT" + (f"  Buffer ID: {buffer_id}" if buffer_id else ""))

    banner("5. ANALYTICS CHECK")
    run([npm, "run", "analytics"], cwd=project, label="Run analytics")

    banner("SUCCESS")
    print("Published/scheduled exactly once:")
    for number in published:
        print(f"  Post {number:03d}")
    if skipped_sent:
        print("Already-sent posts skipped:")
        for number in skipped_sent:
            print(f"  Post {number:03d}")
    print("\nSafe to rerun this script: SENT and UNCERTAIN posts will not be resubmitted automatically.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nCancelled by user.")
        sys.exit(130)
